<a href="https://colab.research.google.com/github/macnya/-Automated-Data-Analysis-Tool/blob/main/APT3025ASSGNT1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.metrics import accuracy_score, classification_report, mean_squared_error, r2_score

In [2]:
df_medical = pd.read_csv('/content/KaggleV2.csv')
df_medical.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No

In [3]:
import os
os.listdir()

['.config', 'KaggleV2.csv', '.ipynb_checkpoints', 'sample_data']

In [4]:
pd.read_csv('KaggleV2.csv')

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,No

In [5]:
print(df_medical.columns)

Index(['PatientId', 'AppointmentID', 'Gender', 'ScheduledDay',
       'AppointmentDay', 'Age', 'Neighbourhood', 'Scholarship', 'Hipertension',
       'Diabetes', 'Alcoholism', 'Handcap', 'SMS_received', 'No-show'],
      dtype='object')

In [6]:
df_medical.isnull().sum()

PatientId         0
AppointmentID     0
Gender            0
ScheduledDay      0
AppointmentDay    0
Age               0
Neighbourhood     0
Scholarship       0
Hipertension      0
Diabetes          0
Alcoholism        0
Handcap           0
SMS_received      0
No-show           0
dtype: int64

In [7]:
df_medical.columns = df_medical.columns.str.strip().str.lower().str.replace(' ', '_')

In [8]:
df_medical.info()
df_medical.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   patientid       110527 non-null  float64
 1   appointmentid   110527 non-null  int64
 2   gender          110527 non-null  object
 3   scheduledday    110527 non-null  object
 4   appointmentday  110527 non-null  object
 5   age             110527 non-null  int64
 6   neighbourhood   110527 non-null  object
 7   scholarship     110527 non-null  int64
 8   hipertension    110527 non-null  int64
 9   diabetes        110527 non-null  int64
 10  alcoholism      110527 non-null  int64
 11  handcap         110527 non-null  int64
 12  sms_received    110527 non-null  int64
 13  no-show         110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB

,patientid,appointmentid,age,scholarship,hipertension,diabetes,alcoholism,handcap,sms_received
count,1.105270e+05,1.105270e+05,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000,110527.000000
mean,1.474963e+14,5.675305e+06,37.088874,0.098266,0.197246,0.071865,0.030400,0.022248,0.321026
std,2.560949e+14,7.129575e+04,23.110205,0.297675,0.397921,0.258265,0.171686,0.161543,0.466873
min,3.921784e+04,5.030230e+06,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.172614e+12,5.640286e+06,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.173184e+13,5.680573e+06,37.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,9.439172e+13,5.725524e+06,55.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,9.999816e+14,5.790484e+06,115.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000

In [9]:
print(df_medical.columns)

Index(['patientid', 'appointmentid', 'gender', 'scheduledday',
       'appointmentday', 'age', 'neighbourhood', 'scholarship', 'hipertension',
       'diabetes', 'alcoholism', 'handcap', 'sms_received', 'no-show'],
      dtype='object')

In [10]:
df_medical['no-show'] = df_medical['no-show'].map({'Yes': 1, 'No': 0})

In [11]:
df_medical = df_medical.drop(columns=['appointmentid', 'patientid'])

In [12]:
df_medical = pd.get_dummies(df_medical, drop_first=True)

In [13]:
print(df_medical.columns)

Index(['age', 'scholarship', 'hipertension', 'diabetes', 'alcoholism',
       'handcap', 'sms_received', 'no-show', 'gender_M',
       'scheduledday_2015-12-03T08:17:28Z',
       ...
       'neighbourhood_SANTOS REIS', 'neighbourhood_SEGURANÇA DO LAR',
       'neighbourhood_SOLON BORGES', 'neighbourhood_SÃO BENEDITO',
       'neighbourhood_SÃO CRISTÓVÃO', 'neighbourhood_SÃO JOSÉ',
       'neighbourhood_SÃO PEDRO', 'neighbourhood_TABUAZEIRO',
       'neighbourhood_UNIVERSITÁRIO', 'neighbourhood_VILA RUBIM'],
      dtype='object', length=103663)

In [14]:
df_medical.columns = df_medical.columns.str.strip().str.lower().str.replace(" ", "_")
print(df_medical.columns)

Index(['age', 'scholarship', 'hipertension', 'diabetes', 'alcoholism',
       'handcap', 'sms_received', 'no-show', 'gender_m',
       'scheduledday_2015-12-03t08:17:28z',
       ...
       'neighbourhood_santos_reis', 'neighbourhood_segurança_do_lar',
       'neighbourhood_solon_borges', 'neighbourhood_são_benedito',
       'neighbourhood_são_cristóvão', 'neighbourhood_são_josé',
       'neighbourhood_são_pedro', 'neighbourhood_tabuazeiro',
       'neighbourhood_universitário', 'neighbourhood_vila_rubim'],
      dtype='object', length=103663)

In [15]:
df_medical.columns = df_medical.columns.str.strip().str.lower().str.replace(" ", "_").str.replace("-", "_")
print(df_medical.columns)

Index(['age', 'scholarship', 'hipertension', 'diabetes', 'alcoholism',
       'handcap', 'sms_received', 'no_show', 'gender_m',
       'scheduledday_2015_12_03t08:17:28z',
       ...
       'neighbourhood_santos_reis', 'neighbourhood_segurança_do_lar',
       'neighbourhood_solon_borges', 'neighbourhood_são_benedito',
       'neighbourhood_são_cristóvão', 'neighbourhood_são_josé',
       'neighbourhood_são_pedro', 'neighbourhood_tabuazeiro',
       'neighbourhood_universitário', 'neighbourhood_vila_rubim'],
      dtype='object', length=103663)

In [16]:
if 'no_show' not in df_medical.columns:
    print("Column 'no_show' not found!")
else:
    print("Column exists, proceeding...")

Column exists, proceeding...

In [17]:
print(df_medical.columns)

Index(['age', 'scholarship', 'hipertension', 'diabetes', 'alcoholism',
       'handcap', 'sms_received', 'no_show', 'gender_m',
       'scheduledday_2015_12_03t08:17:28z',
       ...
       'neighbourhood_santos_reis', 'neighbourhood_segurança_do_lar',
       'neighbourhood_solon_borges', 'neighbourhood_são_benedito',
       'neighbourhood_são_cristóvão', 'neighbourhood_são_josé',
       'neighbourhood_são_pedro', 'neighbourhood_tabuazeiro',
       'neighbourhood_universitário', 'neighbourhood_vila_rubim'],
      dtype='object', length=103663)